name: india_covid_leads
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_spinkit: ^5.0.0
  modal_progress_hud: ^0.1.3
  font_awesome_flutter:
  url_launcher: ^5.6.0
  fluttertoast: ^8.0.6
  shared_preferences: ^2.0.5
  http: ^0.13.2
  dropdownfield: ^1.0.3
  toggle_switch: ^0.1.9
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  flutter_switch: ^0.3.1


flutter:
  uses-material-design: true


  assets:
    - images/
